### ISSUE TITLE
 No rule to make target src/webfrontend/CustomDataTypeGEONAMES.coffee.js

### ISSUE THREAD

**Issue by KlausThornProgrammfabrik** [programmfabrik/easydb-custom-data-type-geonames#2]
The filename is CustomDataTypeGeoname.coffee.js but the Makefile refers to CustomDataTypeGEONAMES.coffee.js, which is then not found.

**Comment by StiftungAusNachlass** [comment]
I suppose it is fixed, otherwise it wouldn't be delivered with easydb..
