### ISSUE TITLE
Verbesserung der Suche?

### ISSUE THREAD

**Issue by lmaylein** [programmfabrik/easydb-custom-data-type-geonames#3]
Lässt sich die Suchfunktion dieses Plugins (oder des Backends) noch verbessern?

Ich gebe mal den "Testbericht" einer Kollegin weiter:

> Wenn ich "Karlstorbahnhof" eingebe erhalte ich keine Treffer, erst " Kulturhaus Karlstorbahnhof" wird gefunden. "Berlin, Alexanderplatz" gibt keinen Treffer, sondern erst "Alexanderplatz"
> Wenn ich "Pinakothek" suche, wird "Alte Pinakothek" nicht in der Trefferliste angezeigt. Außerdem habe ich nicht alles gefunden, obwohl es bei GeoNames vorhanden ist, z.B. "Place de la concorde" oder "Piazza del Campo".

**Comment by StiftungAusNachlass** [comment]
Inzwischen durch neuen Endpoint /geonames2 gefixed.

**Comment by lmaylein** [comment]
Danke. "Berlin Alexanderplatz" scheint aber noch nicht zu gehen, oder?

**Comment by StiftungAusNachlass** [comment]
Danke für den Hinweis! Bei der Suche nach "Alexander" in Deutschland ist der Alexanderplatz unter den top 50. Den "Alexanderplatz" findet man allerdings am besten über die Eingrenzung auf "Platz". 

Die Möglichkeit nach geonames-"Featurecodes" einzuschränken gab es bisher (im Plugin) nicht. Wir haben das entsprechend ergänzt: Es gibt nun eine neue Maskenkonfiguration für die Anzeige eines weiteren Dropdowns "Ortstyp" (vgl. https://www.geonames.org/export/codes.html). Die Änderung erscheint mit dem nächsten easydb5-Release.

Dann findet sich der Alexanderplatz über Suche nach "Alexanderplatz" und Eingrenzung auf Featurecode "SQR" (Platz). Die kombinierte Suche "Berlin Alexanderplatz" und "Alexanderplatz Berlin" ist so bisher nicht möglich, da der zugrunde liegende Dienst eher ein Suggestdienst ist. Kombinationen aus einem Featurenamen und einem beliebigen Elternelement sind bisher nicht vorgesehen. Wir behalten das aber für zukünftige Weiterentwicklungen im Hinterkopf.
