### ISSUE TITLE
conceptFulltext enthält nicht geonameId, adminName1, adminName2, ...

### ISSUE THREAD

**Issue by KlausThornProgrammfabrik** [programmfabrik/easydb-custom-data-type-geonames#4]
Andreas Blobelt und ich haben das Plugin von github verwendet und erwartet dass mit einem validen user dann die Attribute geonameId, adminName1, adminName2, ... gespeichert werden.

Laut unserem Test werden sie das leider nicht. Test-Ablauf:
- Im Datenmodell für das Feld ein geonames-username gespeichert: andreaspf_7
- Zu einem Objekt den Ort Zürich (sitz eines Verwaltungs...) ausgewählt und gespeichert
- Den Datensatz als XML exportiert

Das XML enthält nur:

```
</object>
<string name="conceptFulltext">Zürich</string>
</custom>
```

Verwenden wir es falsch? Hinweise?

gerne Kontakt aufnehmen: andreas.blobelt@programmfabrik.de

**Comment by StiftungAusNachlass** [comment]
Inzwischen werden im Feld _fulltext.text die oben genannten Attribute gespeichert und sind damit auch über die Suche findbar.

**Comment by StiftungAusNachlass** [comment]
Leider kann ich mit meinen Rechten hier nur auf "Close" drücken und nicht auf sowas wie fixed. Deshalb: Closed
